#Copyright [2024] [Robert Fudge]
#SPDX-FileCopyrightText: © 2024 Robert Fudge <rnfudge@mun.ca>
#SPDX-License-Identifier: {Apache-2.0}

#For now all directories should be given with the absolute path

#---------Initialization---------#
init:
  #Target Architecture - valid choices are "arm64" or "amd64"
  arch: "arm64"

  #ROS2 Humble nodes
  gnss: False                                                                                               #Enable GNSS
  zed: True                                                                                                 #Enable ZED Camera
  qhy5III: False                                                                                            #Enable qhy5III
  fcc: False                                                                                                #Enable Flight Control Computer
  calib: False                                                                                              #Enable Camera calibration module (For qhy or other USB webcam)
  foxglove: True                                                                                            #Enable Foxglove Bridge
  static_tf: False                                                                                          #Enable Static Transform

  #ISAAC ROS GEM's
  vslam: False                                                                                               #Enable Visual SLAM
  od: False                                                                                                 #Enable Object Detection
  sr: False                                                                                                 #Enable Nvblox Scene Reconstruction

  #System modules
  monitor: True                                                                                             #Enable monitor module
  controller: False                                                                                         #Enable Controller module
  director: False                                                                                           #Enable Director module

#---------Configuration---------#
config:
  ##########Device Configuration##########
  #GNSS configuration parameters
  gnss: False

  #ZED configuration parameters https://www.stereolabs.com/docs/video/camera-controls
  zed:
    model: "zed2i"                                                                                          #Camera Model
    width: 1280                                                                                              #Mono sensor width (pixels)
    height: 720                                                                                             #Mono sensor height (pixels)
    cam_hz: 60.0                                                                                           #Min 1Hz Max 100Hz
    imu_hz: 400.0                                                                                           #Min 30.0 Max 400.0

    f_x: 527.886474609375                                                                                   #Approximate focal parameter (x-dir, should be same for most ZED cameras)
    f_y: 527.886474609375                                                                                   #Approximate focal parameter (y-dir, should be same for most ZED cameras)

  #qhy5III configuration parameters
  qhy5III:
    camera_settings: "/home/auv-deployment/ros_ws/src/auv_deployment_tools_ros2/config/qhy_params.yaml"       #Directory specifying configuration parameters
    camera_info: ""                                                                                           #File containing calibration settings

  #Flight control computer configuration parameters
  fcc:

  #Calibration node configuration parameters
  calib:

  #Foxglove Bridge configuration parameters
  foxglove:
    num_threads: 2
    buff_size : 200

  ##########GEM Configuration##########

  #VSLAM configuration parameters
  vslam:
    viz: True                                                                                             #Enable visualization (Not needed for deployment)

  #Object detection configuration parameters
  od:
    model_path: "/home/auv-deployment/ros_ws/src/auv_deployment_tools_ros2/adtr2/adtr2_models/models/ONNX/yolo11n.onnx"   #Path to onnx model file (generated by Ultralytics)
    engine_path: "/home/auv-deployment/ros_ws/src/auv_deployment_tools_ros2/adtr2/adtr2_models/models/TRT/yolo11n.trt"       #Path to engine file (generated by TRTExec)
    viz: True
  #Scene Reconstruction configuration parameters
  sr:

  ##########System Module Configuration##########



#---------Storage---------#
storage:
  destination: "/home/auv-deployment/ros_ws/data"                                                           #Path to data storage location

  gnss:
    enabled: True                                                                                           #Whether GNSS recording should be enabled or disabled
    topics:
      - "/fix"

  qhy5III:
    enabled: False
    topics:
      -

  zed:
    enabled: True
    topics:
      -

  vslam:
    enabled: True
    topics:
      -

  od:
    enabled: False
    topics:
      -

  sr:
    enabled: False
    topics:
      -

